### ISSUE TITLE
Entering invalid text causes an error

### ISSUE THREAD

**Issue by khodges42** [luisbraganca/fake-terminal-website#1]
Echoing something like `cat about` will cause a `str not found` error. 

My cheap fix was just to add a default to text, but there's probably a better way.

`    Terminal.prototype.type = function (text = "I can't let you do that, Tom.", callback) {
        this.typeSimulator.type(text, callback);
};`

**Comment by luisbraganca** [comment]
Sorry for the waiting. I managed to fix it, I did some mistake on the if/else block.
Thank you for your observation.
